#配置视图解析器
spring:
  datasource:
    url: jdbc:mysql://120.55.192.190:3306/mymall?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: mall
    password: mymall
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  servlet:
    jsp:
      init-parameters:
        development: true   #用于实现JSP页面热部署

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xmu.www.mymall.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true